### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by codinglifestyle** [billpratt/CloseTabsToRight#1]
I use this feature often and hope you will consider supporting VS2017 soon.

**Comment by billpratt** [comment]
Yes, I am working on VS2017 support now. I hope to have something soon.

**Comment by billpratt** [comment]
@codinglifestyle I have uploaded v1.1 to the marketplace which supports VS 2015 and 2017. Please let me know if you have any issues on this. If everything looks good, please feel free to close the issue.

**Comment by codinglifestyle** [comment]
Brilliant, thanks a million!
