### ISSUE TITLE
Close - To the left

### ISSUE THREAD

**Issue by scar80** [billpratt/CloseTabsToRight#2]
Hi,
I would like to implement close to the left. Should I add feature to your project or create a new one?

**Comment by billpratt** [comment]
That is one feature I considered but never got around to. Id be happy to review a pull request if you want to submit it for this project.

**Comment by billpratt** [comment]
Close Tabs to the Left is now available with v1.2

https://marketplace.visualstudio.com/items?itemName=billpratt.CloseTabsToRight
