### ISSUE TITLE
Can't have multiple tabs of the same file open

### ISSUE THREAD

**Issue by mpulkki** [billpratt/CloseTabsToRight#3]
### Installed product versions
- Visual Studio: 2017, 2015
- This extension: 1.1.0

### Description
Extension doesn't work if multiple tabs of the same file are open. User is greeted with the following error message: "An item with the same key has already been added".

### Steps to recreate (VS2017)
1. Open a second instance of a file from "Window -> New Window".
2. Try to click "Close Tabs to the Right" on any open tab

**Comment by jizc** [comment]
I can confirm this is still an issue in v1.2.0, for both "Close Tabs to the Right" and "Close Tabs to the Left".

**Comment by eurubkov** [comment]
Hi! I submitted a PR to address this issue if the repo is still active. I wasn't able to link it to this issue for some reason though.

**Comment by billpratt** [comment]
Apologizes for the late reply. For some reason I never got the notification of PR. I'll take a look. Thanks for contributing!

**Comment by billpratt** [comment]
@eurubkov - Thanks for making these changes!

 This has been approved and merged. Version 1.4 is uploaded and should be available soon
